Update link.yml

diff --git a/.github/workflows/link.yml b/.github/workflows/link.yml
--- a/.github/workflows/link.yml
+++ b/.github/workflows/link.yml
@@ -25,13 +25,14 @@ jobs:
         
         URL=https://$DEPLOYMENT/
         echo "Checking links in $URL"
+        octopus $URL
 
         # Run octopus and catch errors for better logging
-        set -e
-        {
-          octopus $URL
-        } || {
-          echo "Error occurred while running octopus"
-          echo "Debugging info: URL=$URL, Deployment=$DEPLOYMENT"
-          exit 1
-        }
+        #set -e
+        #{
+        #  octopus $URL
+        #} || {
+        #  echo "Error occurred while running octopus"
+        #  echo "Debugging info: URL=$URL, Deployment=$DEPLOYMENT"
+        #  exit 1
+        #}
